name: Close milestone
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Needs to match, exactly, the name of a milestone
  workflow_call:
    inputs:
      version_call:
        description: Needs to match, exactly, the name of a milestone
        required: true
        type: string
    secrets:
      token:
        required: true
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v3
        with:
          repository: "grafana/grafana-github-actions"
          path: ./actions
          ref: main
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Close milestone (manually invoked)
        if: ${{ github.event.inputs.version != '' }}
        uses: ./actions/close-milestone
        with:
          token: ${{ secrets.GH_BOT_ACCESS_TOKEN }}
      - name: Close milestone (workflow invoked)
        if: ${{ inputs.version_call != '' }}
        uses: ./actions/close-milestone
        with:
          version_call: ${{ inputs.version_call }}
          token: ${{ secrets.token }}
